http:
    port: 8080
    adminPort: 8081
    minThreads: 20
    maxThreads: 20
    connectorType: blocking
    maxIdleTime: 60s
    acceptorThreads: 1
    acceptQueueSize: -1
    reuseAddress: true
    requestLog:
        console:
          enabled: false

logging:
    level: INFO


redisHostName: localhost:6379,localhost:6380
maxRedisConnections: 200
esClusterName: vinod-es-11
esClusterUnicastHosts: localhost
executorPoolSize: 60
